language: python
python:
    - "2.7"
    - "2.6"

branches:
    only:
        - master

install:
    - pip install inspektor pylint autopep8
    - pip install -r requirements.txt
    - if [ $TRAVIS_PYTHON_VERSION == '2.6' ]; then pip install -r requirements-python26.txt; fi

script:
    - ./scripts/avocado-server-manage test
    - ./selftests/modules_boundaries
    - inspekt lint
    - inspekt style
